### ISSUE TITLE
Support for cache policy for static assets

### ISSUE THREAD

**Issue by nathanchase** [exreplay/nuxt-compression#1]
It would be great to be able to pass:
`export const maxAge = 60 * 60 * 24 * 365;`
to the assets that this module is compressing.

Even better, custom maxAge values for different filetypes.

**Comment by exreplay** [comment]
We could implement a `maxAge` option which either accepts a number or a filter function or we could provide a `cacheControl` option which accepts a string or a filter function.

```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  compression: {
    maxAge: 60 * 60 * 24 * 365,
    maxAge: assetPath => assetPath.endsWith('.mjs') ? 60 * 60 * 24 * 365 : 60,
    cacheControl: `max-age=${60 * 60 * 24 * 365}, immutable`,
    cacheControl: assetPath => assetPath.endsWith('.mjs') ? `max-age=${60 * 60 * 24 * 365}, immutable` : `max-age=${60}, immutable`
  }
})
```

The `maxAge` option is simpler and foolproof but if you want to get the most out of caching, the `cacheControl` option gives you all the freedom.

We could also implement both options. The module would then decide depending on what the user set. Preferring the `cacheControl` option over `maxAge`. Having the ability to have both options coexist would make the output unpredictable and too complex.

If only the `maxAge` is set it would set the following `Cache-Control` header `max-age=31536000, immutable`.

@nathanchase  What do you think?

**Comment by nathanchase** [comment]
Yeah, I think this is a great approach to have more configurability directly on `Cache-Control`. There's a great flowchart at https://web.dev/http-cache/#flowchart that somewhat indicates a best practice methodology.

`ETag` and `Last-Modified` will likely come up as additions, too. 

More at: 
https://web.dev/http-cache/
https://web.dev/codelab-http-cache/

**Comment by exreplay** [comment]
Thanks for the hint. I will complete the current PR with the `maxAge` and `cacheControl` options and then add support for `ETag` and `Last-Modified` for the compressed assets.
